---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: schabiyo/ossdemo
    tag: latest

params:
  acr_repository:
  acr_username:
  acr_password:


inputs:
  - name: web-nodejs

run:
  path: web-nodejs/ci/tasks/build-and-test.sh
